[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["tests"]

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
test-extras = ["test"]
test-skip = ["*universal2:arm64"]

[tool.cibuildwheel.linux]
before-all = [
    "yum install -y gcc",
]
before-build = [
    "rm -rf {project}/build",
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan profile update settings.compiler.libcxx=libstdc++11 default",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]

[tool.cibuildwheel.windows]
before-build = [
    "rm -rf {project}/build",
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
    "echo %cd%"
]

[tool.cibuildwheel.macos]
before-build = [
    "rm -rf {project}/build",
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing"
]