[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]

[tool.cibuildwheel]
test-command = "pytest {project}/python/tests"

[tool.cibuildwheel.linux]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan profile update settings.compiler.libcxx=libstdc++11 default",
    "conan config set general.revisions_enabled=1",
    "conan install ninja/1.11.0@",
    "conan install . --build=missing",
    "pwd"
]

[tool.cibuildwheel.windows]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
    "echo %cd%"
]

[tool.cibuildwheel.macos]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
    "pwd"
]