[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/python/tests"
test-extras = "test"
archs = ["auto64"]
skip = ["cp36-*", "cp37-*", "cp39-*", "cp311-*", "cp312-*", "pp*"]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-ppc64le-image = "manylinux_2_28"
manylinux-s390x-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
manylinux-pypy_aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"
musllinux-ppc64le-image = "musllinux_1_2"
musllinux-s390x-image = "musllinux_1_2"
build-verbosity = 3

[tool.cibuildwheel.linux]
before-build = [
    "rm -rf {project}/build/lib.*",
    "rm -rf {project}/build/temp.*",
    "rm -rf {project}/build/bdist.*",
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan profile update settings.compiler.libcxx=libstdc++11 default",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]

[tool.cibuildwheel.windows]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]

[tool.cibuildwheel.macos]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]