[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[project]
name = "hydrobricks"
version = "0.0.2"
authors = [
    { name = "Pascal Horton", email = "pascal.horton@giub.unibe.ch" },
]
description = "A modular hydrological modelling framework"
readme = "python/README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "pandas",
    "pyyaml",
    "netCDF4",
    "matplotlib",
    "pytest"
]

[project.urls]
"Homepage" = "https://github.com/hydrobricks/hydrobricks"
"Bug Tracker" = "https://github.com/hydrobricks/hydrobricks/issues"

[flake8]
max-line-length = 88

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/python/tests"
test-extras = "test"
archs = ["auto64"]
skip = ["*musllinux*", "cp36-*", "cp37-*", "cp39-*", "cp311-*", "cp312-*", "pp*"]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-ppc64le-image = "manylinux_2_28"
manylinux-s390x-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
manylinux-pypy_aarch64-image = "manylinux_2_28"
build-verbosity = 3

[tool.cibuildwheel.linux]
before-build = [
    "rm -rf {project}/build/lib.*",
    "rm -rf {project}/build/temp.*",
    "rm -rf {project}/build/bdist.*",
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan profile update settings.compiler.libcxx=libstdc++11 default",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]

[tool.cibuildwheel.windows]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]

[tool.cibuildwheel.macos]
before-build = [
    "pip install conan",
    "pip show conan",
    "conan profile new default --detect --force",
    "conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force",
    "conan config set general.revisions_enabled=1",
    "conan install . --build=missing",
]
