coverage:
  precision: 2
  round: nearest
  range: "20...100"
  status:
    project:
      default:
        target: 75
        threshold: 1
        base: auto
fixes:
  - "/home/runner/work/flhy/flhy/::"
