name: Python Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - feature/*
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries
      run: sudo apt-get install tree python

    - name: Cache Conan libs
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: /home/runner/.conan
        key: ${{ runner.os }}-conan

    - name: Setup Conan
      run: |
        pip install conan
        if grep -q "default" <<< $(conan profile list); then
          echo "Conan default profile already exists."
        else
          conan profile new default --detect
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan
        fi
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan config set general.revisions_enabled=1

    - uses: pypa/cibuildwheel@v2.9.0
      env:
        CIBW_ARCHS_MACOS: auto universal2

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.pypi_password }}
