name: Python Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.6", "3.8", "3.11-dev"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Conan libs
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: /home/runner/.conan
        key: ${{ runner.os }}-conan

    - name: Setup Conan
      run: |
        pip install conan
        if grep -q "default" <<< $(conan profile list); then
          echo "Conan default profile already exists."
        else
          conan profile new default --detect
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan
        fi
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan config set general.revisions_enabled=1

    - name: Get dependencies
      run: conan install . --build=missing

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
